<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FaceForge.Core</AssemblyName>
    <RootNamespace>FaceForge.Core</RootNamespace>
    <Version>0.6.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.47.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FaceForge.Core.Tests" />
  </ItemGroup>
</Project>
